/*
Copyright (C) 2023-2026 QuantumNous

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program. If not, see <https://www.gnu.org/licenses/>.

For commercial licensing, please contact support@quantumnous.com
*/
import {
  ArrowLeft01Icon,
  ArrowRight01Icon,
  UserMultiple02Icon,
} from '@hugeicons/core-free-icons'
import { HugeiconsIcon } from '@hugeicons/react'
import { useTranslation } from 'react-i18next'

import { Button } from '@/components/ui/button'
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from '@/components/ui/card'
import { Skeleton } from '@/components/ui/skeleton'
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table'
import { formatQuota } from '@/lib/format'

import type { ReferralInvitedUsersPage } from '../types'

type InvitedUsersCardProps = {
  data?: ReferralInvitedUsersPage
  loading: boolean
  page: number
  onPageChange: (page: number) => void
}

function formatTimestamp(timestamp: number, emptyText: string): string {
  if (!timestamp) return emptyText
  return new Date(timestamp * 1000).toLocaleString()
}

export function InvitedUsersCard(props: InvitedUsersCardProps) {
  const { t } = useTranslation()
  const items = props.data?.items ?? []
  const pageSize = props.data?.page_size ?? 10
  const total = props.data?.total ?? 0
  const pageCount = Math.max(1, Math.ceil(total / pageSize))

  return (
    <Card data-card-hover='false'>
      <CardHeader>
        <CardTitle>{t('Invited users')}</CardTitle>
        <CardDescription>
          {t(
            'Track registrations, credited top-ups, and commission generated by each invited user.'
          )}
        </CardDescription>
      </CardHeader>
      <CardContent className='px-0'>
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead className='pl-6'>{t('User')}</TableHead>
              <TableHead>{t('Joined at')}</TableHead>
              <TableHead className='text-right'>{t('Top-ups')}</TableHead>
              <TableHead className='text-right'>
                {t('Credited balance')}
              </TableHead>
              <TableHead className='text-right'>
                {t('Commission earned')}
              </TableHead>
              <TableHead className='pr-6 text-right'>
                {t('Last commission')}
              </TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {props.loading
              ? Array.from({ length: 5 }, (_, index) => (
                  <TableRow key={index}>
                    <TableCell className='pl-6'>
                      <Skeleton className='h-8 w-36' />
                    </TableCell>
                    <TableCell>
                      <Skeleton className='h-4 w-28' />
                    </TableCell>
                    <TableCell>
                      <Skeleton className='ml-auto h-4 w-10' />
                    </TableCell>
                    <TableCell>
                      <Skeleton className='ml-auto h-4 w-24' />
                    </TableCell>
                    <TableCell>
                      <Skeleton className='ml-auto h-4 w-24' />
                    </TableCell>
                    <TableCell className='pr-6'>
                      <Skeleton className='ml-auto h-4 w-28' />
                    </TableCell>
                  </TableRow>
                ))
              : items.map((user) => (
                  <TableRow key={user.id}>
                    <TableCell className='pl-6'>
                      <div className='min-w-36'>
                        <p className='font-medium'>
                          {user.display_name || user.username}
                        </p>
                        <p className='text-muted-foreground text-xs'>
                          @{user.username}
                        </p>
                      </div>
                    </TableCell>
                    <TableCell>
                      {formatTimestamp(user.created_at, '-')}
                    </TableCell>
                    <TableCell className='text-right'>
                      {user.top_up_count}
                    </TableCell>
                    <TableCell className='text-right font-medium'>
                      {formatQuota(user.recharge_quota_total)}
                    </TableCell>
                    <TableCell className='text-right font-medium'>
                      {formatQuota(user.commission_quota_total)}
                    </TableCell>
                    <TableCell className='pr-6 text-right'>
                      {formatTimestamp(
                        user.last_commission_at,
                        t('No top-up yet')
                      )}
                    </TableCell>
                  </TableRow>
                ))}
          </TableBody>
        </Table>

        {!props.loading && items.length === 0 ? (
          <div className='flex flex-col items-center gap-2 px-6 py-12 text-center'>
            <HugeiconsIcon
              icon={UserMultiple02Icon}
              strokeWidth={1.5}
              className='text-muted-foreground size-10'
            />
            <p className='font-medium'>{t('No invited users yet')}</p>
            <p className='text-muted-foreground max-w-sm text-sm'>
              {t(
                'Share your referral link. New users who register through it will appear here.'
              )}
            </p>
          </div>
        ) : null}
      </CardContent>
      {total > pageSize ? (
        <CardFooter className='justify-between border-t pt-4'>
          <p className='text-muted-foreground text-sm'>
            {t('Page {{page}} of {{pageCount}}', {
              page: props.page,
              pageCount,
            })}
          </p>
          <div className='flex gap-2'>
            <Button
              type='button'
              variant='outline'
              size='icon-sm'
              disabled={props.page <= 1 || props.loading}
              onClick={() => props.onPageChange(props.page - 1)}
              aria-label={t('Previous page')}
            >
              <HugeiconsIcon icon={ArrowLeft01Icon} strokeWidth={2} />
            </Button>
            <Button
              type='button'
              variant='outline'
              size='icon-sm'
              disabled={props.page >= pageCount || props.loading}
              onClick={() => props.onPageChange(props.page + 1)}
              aria-label={t('Next page')}
            >
              <HugeiconsIcon icon={ArrowRight01Icon} strokeWidth={2} />
            </Button>
          </div>
        </CardFooter>
      ) : null}
    </Card>
  )
}
